export const countryTypes = {
  FETCH_COUNTRY_DATA_START: "FETCH_COUNTRY_DATA_START",
  FETCH_COUNTRY_DATA_SUCCESS: "FETCH_COUNTRY_DATA_SUCCESS",
  FETCH_COUNTRY_DATA_FAILURE: "FETCH_COUNTRY_DATA_FAILURE",
};
